apiVersion: v1
kind: Secret
metadata:
    name: mongo-secret
type: Opaque
data:
    mongo-port: NTU1NQ==
    mongo-url:  bW9uZ29kYitzcnY6Ly9yYWppdHNocmVzdGhhNjQ2OnNuaGZ1R0hMVXNiVlA0eEpAY2x1c3RlcjAuZTV0bGs0aS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjBjbA==

